### PR TITLE
[WIP] [Ruby] Use variants

### PR DESCRIPTION
**Pull request by waghanza**
Hi @ioquatix @bo,

I am introducing a big change `here`, **benchmarking** all `ruby` **frameworks** with 

+ https://github.com/socketry/falcon
+ https://github.com/boazsegev/iodine

List of frameworks :
+ [ ] agoo  
+ [ ] camping
+ [ ] cuba
+ [ ] flame
+ [ ] grape
+ [ ] hanami
+ [ ] plezi
+ [ ] rack-routing
+ [x] rails
+ [ ] roda
+ [x] sinatra
+ [x] syro

I will update results on https://github.com/waghanza/http-benchmark/blob/ruby_variants/README.md#results

Regards,

### CODE REVIEW

**Comment by ioquatix** [comment]
Awesome let me know how it goes!

**Comment by waghanza** [comment]
@ioquatix Seems that `falcon` is not **always** the fastest, depending of which **framework** is involved

|    | Language | Framework | Engine | Speed (`req/s`) | Horizontal scale (parallelism) | Vertical scale (concurrency) |
|----|----------|-----------|--------|----------------:|-------------|-------------|
| 1 | ruby (2.6)| [syro](https://github.com/soveran/syro) (3.1) | puma | 40 552 | | |
| 2 | ruby (2.6)| [syro](https://github.com/soveran/syro) (3.1) | falcon | 35 211 | | |
| 3 | ruby (2.6)| [syro](https://github.com/soveran/syro) (3.1) | iodine | 27 345 | | |
| 4 | ruby (2.6)| [sinatra](https://sinatrarb.com) (2.0) | iodine | 21 230 | | |
| 5 | ruby (2.6)| [sinatra](https://sinatrarb.com) (2.0) | falcon | 15 257 | | |
| 6 | ruby (2.6)| [sinatra](https://sinatrarb.com) (2.0) | puma | 14 996 | | |
| 7 | ruby (2.6)| [rails](https://rubyonrails.org) (6.0) | iodine | 4 232 | | |
| 8 | ruby (2.6)| [rails](https://rubyonrails.org) (6.0) | falcon | 4 043 | | |
| 9 | ruby (2.6)| [rails](https://rubyonrails.org) (6.0) | puma | 3 935 | | |

**Comment by ioquatix** [comment]
What tool did you use for benchmarking and what was the level of concurrency?

**Comment by waghanza** [comment]
I use `wrk`, the whole command line was
~~~sh
wrk --latency --duration 5s --connections 500 --timeout 8 --threads 8 http://172.17.0.2:3000/
~~~

I mot an expert of this kind of stuff, feel free to perticipate in https://github.com/the-benchmarker/web-frameworks/issues/2182 then :heart:

**Comment by ioquatix** [comment]
I will try to reproduce your results.

**Comment by ioquatix** [comment]
`--connections 500` probably doesn't give you a good benchmark. I'd suggest sweeping 1, 2, 4, 8, 16, 32, 64, 128, etc. Also, `wrk` and `puma` used to have a bug when measuring latency, because puma would effectively only serve the first N connections (N = number of workers). The rest of the connections would block indefinitely (infinite latency). So, `wrk` always reported, e.g. 10ms latency with 1 connection, 10 connections or 10000 connections, which is impossible.

**Comment by ioquatix** [comment]
I reported on the issue here: https://www.youtube.com/watch?v=2u6JRvKh7Dg

**Comment by waghanza** [comment]
I don't understand @ioquatix 

do you suggest to use an other values for `--connections` ? or multiple values ?

**Comment by ioquatix** [comment]
If you look at the graphs on the page: https://github.com/socketry/falcon-benchmark

You will see `--connections N` is on the X axis. Because servers behave differently depending on concurrency level. A server that performs great with 1 connection might be completely crap with 100, or vice versa.

So, your dimension of testing is a bit limited because you are hard coding `--connections 500`.

If you look at my graph, you will see around `--connections 16` most servers perform pretty well, e.g. puma, passenger, falcon, etc. But if you go to `--connections 512`, puma performs about half as well, passenger performance has dropped through the floor.

So, your benchmark is not representing the behaviour of servers very well, since that behaviour can be highly dependent on the number of active connections.

Let me know if you want more details.

**Comment by ioquatix** [comment]
Also, you should consider using this fork of `wrk`. The original `wrk` is unmaintained for a long time. It's not a great tool for benchmarking, it has serious issues in the latency calculations as shown in my live stream (linked above).

https://github.com/ioquatix/wrk

**Comment by waghanza** [comment]
@ioquatix Thanks for those information. :+1: 

I understand that the results shown `here` could be wrong because of this `concurrency` level.

However, it might add more complexity to test on various concurrency level. At least the purpose of this project, is to show how technologies could perform in **real-life**.

I am not sure if having a concurrency of `512` (**example**) could reflect a **real-life** application, but on the other hand, I am not sure neither that results will be understandable if you add more concurrency level.

**Comment by ioquatix** [comment]
I would suggest testing with connections = N^2 where N is the number of CPU cores.

**Comment by ioquatix** [comment]
Make sure you set the number of threads to wrk to be N.

**Comment by waghanza** [comment]
@ioquatix You mean that `wrk --latency --duration 5s --connections 64 --timeout 8 --threads 8 http://172.17.0.2:3000/` show better results (for a `8` cores machine) ?

**Comment by ioquatix** [comment]
I think it's a slightly more realistic default... but like I said the response of servers changes depending on the level of concurrency.

**Comment by waghanza** [comment]
@ioquatix I've updated results https://github.com/the-benchmarker/web-frameworks#results using your fork and changing settings to above command

btw, thanks for the tips around having multiple concurrency levels

**Comment by waghanza** [comment]
a question, if you mind, when you say

> I would suggest testing with connections = N^2 where N is the number of CPU cores.

do you suggest using N^2 CPU cores of **server** or **sieging machine** ?

**Comment by ioquatix** [comment]
Okay, here is the rational.

On the sieging machine, you should use N threads, N^2 connections, for N cores. I think this should scale up gracefully as you increase core count. You definitely want one thread per core, and you want a handful of connections per thread. You could hold it constant, e.g. 8 connections per thread. But I guess, if you are using a 16 core system, which gives you 256 connections, seems about right to me.

On the server, depending on how it's configured you definitely want at least one process/thread per processor. On servers which use threads for both parallelism and concurrency, N processes with N workers gives you the same relationship. With Falcon, in theory you only need N processes and 1 event loop per core.

In order to report on this, probably worth looking at load average during the test. To capture whether the server was actually able to utilise the hardware. Even if you report "xx req/s" if the load average was not N when on a N core system, the server is not working efficiently.

**Pull request closed without merging**
